### ISSUE TITLE
createPredicate throws an error with erroneous message if type of field is not string, number or boolean

### ISSUE THREAD

**Issue by misterdjules** [joyent/node-krill#10]
```
$ node -e "var mod_krill = require('./lib/krill.js'); mod_krill.createPredicate({eq: ['foo', null]});"

/Users/JulienGilli/dev/sdc/node-krill/lib/krill.js:464
		throw (new VError('predicate %j: field "%s" is not a string, ' +
		       ^
VError: predicate { eq: [ 'foo', null ] }: field "eq" is not a string, number, or boolean
    at RelationalOperator.krillPrimValidateRel [as validate] (/Users/JulienGilli/dev/sdc/node-krill/lib/krill.js:464:10)
    at krillPrimValidateSyntax (/Users/JulienGilli/dev/sdc/node-krill/lib/krill.js:422:16)
    at Object.createPredicate (/Users/JulienGilli/dev/sdc/node-krill/lib/krill.js:25:2)
    at [eval]:1:54
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:565:25)
    at startup (node.js:80:7)
    at node.js:935:3
$
```

Instead of `predicate { eq: [ 'foo', null ] }: field "eq" is not a string, number, or boolean`, the error message should be `predicate { eq: [ 'foo', null ] }: field "foo" is not a string, number, or boolean`.

**Comment by misterdjules** [comment]
Will submit a CR to Gerrit once https://cr.joyent.us/#/c/2089/ is merged.

**Comment by misterdjules** [comment]
CR at https://cr.joyent.us/#/c/2091.

**Comment by misterdjules** [comment]
In order to test those changes, I ran `make prepush`: all tests passed and it exited with a 0 exit code.

**Comment by misterdjules** [comment]
Fixed by https://github.com/joyent/node-krill/commit/3c520d5a5e9884c264899cea6950be46b8d94225.
